/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cx.ring.daemon;

public class StringVect extends java.util.AbstractList<String> {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected StringVect(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(StringVect obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RingserviceJNI.delete_StringVect(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public StringVect() {
    this(RingserviceJNI.new_StringVect__SWIG_0(), true);
  }

  public StringVect(long n) {
    this(RingserviceJNI.new_StringVect__SWIG_1(n), true);
  }

  public long capacity() {
    return RingserviceJNI.StringVect_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    RingserviceJNI.StringVect_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return RingserviceJNI.StringVect_isEmpty(swigCPtr, this);
  }

  public void clear() {
    RingserviceJNI.StringVect_clear(swigCPtr, this);
  }

  public String get(int i) {
    return RingserviceJNI.StringVect_get(swigCPtr, this, i);
  }

  public String set(int i, String in) {
    return RingserviceJNI.StringVect_set(swigCPtr, this, i, in);
  }

  public boolean add(String in) {
    return RingserviceJNI.StringVect_add(swigCPtr, this, in);
  }

  public int size() {
    return RingserviceJNI.StringVect_size(swigCPtr, this);
  }

}
