/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cx.ring.daemon;

public class VectMap {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected VectMap(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VectMap obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RingserviceJNI.delete_VectMap(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public java.util.ArrayList<java.util.Map<String, String>> toNative() {
    java.util.ArrayList<java.util.Map<String, String>> out = new java.util.ArrayList<>();
    for (int i = 0; i < size(); ++i) {
        out.add(get(i).toNative());
    }
    return out;
  }

  public VectMap() {
    this(RingserviceJNI.new_VectMap__SWIG_0(), true);
  }

  public VectMap(long n) {
    this(RingserviceJNI.new_VectMap__SWIG_1(n), true);
  }

  public long size() {
    return RingserviceJNI.VectMap_size(swigCPtr, this);
  }

  public long capacity() {
    return RingserviceJNI.VectMap_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    RingserviceJNI.VectMap_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return RingserviceJNI.VectMap_isEmpty(swigCPtr, this);
  }

  public void clear() {
    RingserviceJNI.VectMap_clear(swigCPtr, this);
  }

  public void add(StringMap x) {
    RingserviceJNI.VectMap_add(swigCPtr, this, StringMap.getCPtr(x), x);
  }

  public StringMap get(int i) {
    return new StringMap(RingserviceJNI.VectMap_get(swigCPtr, this, i), false);
  }

  public void set(int i, StringMap val) {
    RingserviceJNI.VectMap_set(swigCPtr, this, i, StringMap.getCPtr(val), val);
  }

}
